In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('/content/1_Churn_Modelling(in).csv')
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [15]:
df.shape

(10000, 14)

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname             object
CreditScore          int64
Geography           object
Gender              object
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
cols=['Surname','Geography','Gender']
for col in cols:
  df[col] = le.fit_transform(df[col])

In [7]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname              int64
CreditScore          int64
Geography            int64
Gender               int64
Age                  int64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [8]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,1115,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,1177,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,2040,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,289,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,1822,850,2,0,43,2,125510.82,1,1,1,79084.10,0

In [9]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [12]:
numeric_cols = ['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited']

outlier_counts = {}

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    outlier_counts[col] = len(outliers)

for col, count in outlier_counts.items():
    print(f"{col}: {count} outliers")

RowNumber: 0 outliers
CustomerId: 0 outliers
Surname: 0 outliers
CreditScore: 15 outliers
Geography: 0 outliers
Gender: 0 outliers
Age: 359 outliers
Tenure: 0 outliers
Balance: 0 outliers
NumOfProducts: 60 outliers
HasCrCard: 0 outliers
IsActiveMember: 0 outliers
EstimatedSalary: 0 outliers
Exited: 2037 outliers

In [17]:
df_cleaned = df.copy()


columns_with_outliers = ['CreditScore', 'Age', 'NumOfProducts', 'Exited']

for col in columns_with_outliers:
    Q1 = df_cleaned[col].quantile(0.25)
    Q3 = df_cleaned[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df_cleaned = df_cleaned[(df_cleaned[col] >= lower_bound) & (df_cleaned[col] <= upper_bound)]

print(f"Shape after removing outliers: {df_cleaned.shape}")

Shape after removing outliers: (7963, 14)

In [19]:
df.dtypes

RowNumber            int64
CustomerId           int64
Surname              int64
CreditScore        float64
Geography            int64
Gender               int64
Age                float64
Tenure               int64
Balance            float64
NumOfProducts        int64
HasCrCard            int64
IsActiveMember       int64
EstimatedSalary    float64
Exited               int64
dtype: object

In [22]:
from sklearn.preprocessing import MinMaxScaler
sl=MinMaxScaler()
df[[ 'CreditScore','Age', 'Tenure', 'Balance', 'NumOfProducts','EstimatedSalary']]=sl.fit_transform(df[['CreditScore','Age', 'Tenure', 'Balance', 'NumOfProducts','EstimatedSalary']])
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,0.0000,0.275616,0.380416,0.505353,0.0,0.0,0.545455,0.2,0.000000,0.0,1.0,1.0,0.506735,1.0
1,0.0001,0.326454,0.401569,0.481799,1.0,0.0,0.522727,0.1,0.334031,0.0,0.0,1.0,0.562709,0.0
2,0.0002,0.214421,0.696008,0.254818,0.0,0.0,0.545455,0.8,0.636357,1.0,1.0,0.0,0.569654,1.0
3,0.0003,0.542636,0.098601,0.676660,0.0,0.0,0.477273,0.1,0.000000,1.0,0.0,0.0,0.469120,0.0
4,0.0004,0.688778,0.621631,1.000000,1.0,0.0,0.568182,0.2,0.500246,0.0,1.0,1.0,0.395400,0.0

In [23]:
df.dtypes

RowNumber          float64
CustomerId         float64
Surname            float64
CreditScore        float64
Geography          float64
Gender             float64
Age                float64
Tenure             float64
Balance            float64
NumOfProducts      float64
HasCrCard          float64
IsActiveMember     float64
EstimatedSalary    float64
Exited             float64
dtype: object

In [24]:
X=df.drop('Exited',axis=1)
y=df['Exited']

In [25]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)